class DelitaxModel {
  String corporateId;
  String corporate;
  String accountId;
  String additionalReffPrefix;
  String refferenceNumber;
  String contractTypeId;
  String alternateRefferenceCode;
  String platformId;
  String companySecurityId;
  String dateOfOperation;
  String agencyBusinessUnitNameId;
  String agencyBranchNameId;
  String languageId;
  String parentCorporateId;
  String businessCurrencyId;
  String addressLine1;
  String addressLine2;
  String addressLine3;
  String sububId;
  String city;
  String stateId;
  String postCode;
  String countryId;
  String pccdPhoneCC;
  String pccdPhoneAC;
  String pccdPhoneNo;
  String pccdPhoneExtn;
  String pccdMobileCC;
  String pccdMobileAC;
  String pccdMobileNo;
  String pccdFaxCC;
  String pccdFaxAC;
  String pccdFaxNo;
  String pccdFaxExtn;
  String mon;
  String tue;
  String wed;
  String thu;
  String fri;
  String sat;
  String sun;
  String all;
  String workingFrom;
  String workingTo;
  String pfmTitleId;
  String pfmFirstName;
  String pfmLastName;
  String pfmDepartment;
  String pfmDesignation;
  String pfmMobileCC;
  String pfmMobileAC;
  String pfmMobileNo;
  String pfmEmail;
  String pfmAltEmail;
  String podReferredBy;
  String podAssociateCrm;
  String podGeneralRemarks;
  String podDeskStaff;
  String podSpecialNotes;
  String podDisclaimer;
  String podServicingTeamName;
  String podPhoneCC;
  String podPhoneAC;
  String podPhoneNo;
  String podPhoneExtn;
  String podTravelDeskDetail;
  String podServicingTeamEmail;
  String psdTitleId;
  String psdFirstName;
  String psdLastName;
  String psdEmail;
  String psdPhoneCC;
  String psdPhoneAC;
  String psdPhoneNo;
  String psdPhoneExtn;
  String psdMobileCC;
  String psdMobileAC;
  String psdMobileNo;
  String pbdbankName;
  String pbdaccountNo;
  String pbdsortCode;
  String pbdbsbNo;
  String pbdbBranchNo;
  String pbdswiftCode;
  String pbdAddress1;
  String pbdAddress2;
  String pbdPhoneCC;
  String pbdPhoneAC;
  String pbdPhoneNo;
  String pbdPhoneExtn;
  String pbdfaxCC;
  String pbdfaxAC;
  String pbdfaxNo;
  String pbdfaxExtn;
  String plmLicenseNo;
  String plmServiceTax;
  String plmAbnNo;
  String plmAbnExtensionNo;
  String plmNpwpNumber;
  String ptTaxNumber;
  String ptTaxOutoffScope;
  String pgstNo;
  String pgstUnitCode;
  String pgstAgencyClassificationId;
  String pgstTitleId;
  String pgstFirstName;
  String pgstLastName;
  String pgstAddressupdate;
  String pgstAgencyName;
  String pgstAgencyAddress;
  String pgstCountryId;
  String pgstStateId;
  String pgstCity;
  String pgstPostCode;
  String pgstHolderEmail;
  String pgstPhoneCC;
  String pgstPhoneAC;
  String pgstPhoneNo;
  String pgstPhoneExtn;
  String corporateLogo;
  String isActive;
  String createdDate;
  String createdBy;
  String modifyDate;
  String modifyBy;
  String username;
  String password;
  String pccdMobileExtn;
  String gstNumber;
  String panNumber;
  String accountName;
  String accountNumber;
  String ifscCode;
  String bankName;
  String bankLocation;
  String agentId;
  String subAgentId;
  String userTypeId;
  String userId;
  String approveStatus;
  String vatNo;
  String corporateName;
  String stateName;
  String country;
  String operationDate;
  String contractType;
  String language;
  String currency;
  String refreshPnr;
  String viewPnr;
  String seatMap;
  String backofficeFile;
  String importBooking;
  String salesReport;
  String issueTicket;
  String cancelBooking;
  String cancelTicket;
  String manageServices;
  String manageElement;
  String changeBooking;
  String viewTicket;
  String downloadDocument;
  String bookingOptions;
  String agencyId;
  String branchId;
  String flightMarkup;
  String hotelMarkup;
  String carMarkup;
  String sightSeeingMarkup;
  String busMarkup;
  String currencyCode;
  String agentName;
  String agencyBranch;
  String businessUnitName;
  String pccdPhoneCountry;
  String pccdMobileCountry;
  String pccdFaxCountry;
  String pfmMobileCountry;
  String psdPhoneCountry;
  String psdMobileCountry;
  String pbdPhoneCountry;
  String pbdfaxCountry;
  String customerType;
  String customerName;

  DelitaxModel({
    required this.corporateId,
    required this.corporate,
    required this.accountId,
    required this.additionalReffPrefix,
    required this.refferenceNumber,
    required this.contractTypeId,
    required this.alternateRefferenceCode,
    required this.platformId,
    required this.companySecurityId,
    required this.dateOfOperation,
    required this.agencyBusinessUnitNameId,
    required this.agencyBranchNameId,
    required this.languageId,
    required this.parentCorporateId,
    required this.businessCurrencyId,
    required this.addressLine1,
    required this.addressLine2,
    required this.addressLine3,
    required this.sububId,
    required this.city,
    required this.stateId,
    required this.postCode,
    required this.countryId,
    required this.pccdPhoneCC,
    required this.pccdPhoneAC,
    required this.pccdPhoneNo,
    required this.pccdPhoneExtn,
    required this.pccdMobileCC,
    required this.pccdMobileAC,
    required this.pccdMobileNo,
    required this.pccdFaxCC,
    required this.pccdFaxAC,
    required this.pccdFaxNo,
    required this.pccdFaxExtn,
    required this.mon,
    required this.tue,
    required this.wed,
    required this.thu,
    required this.fri,
    required this.sat,
    required this.sun,
    required this.all,
    required this.workingFrom,
    required this.workingTo,
    required this.pfmTitleId,
    required this.pfmFirstName,
    required this.pfmLastName,
    required this.pfmDepartment,
    required this.pfmDesignation,
    required this.pfmMobileCC,
    required this.pfmMobileAC,
    required this.pfmMobileNo,
    required this.pfmEmail,
    required this.pfmAltEmail,
    required this.podReferredBy,
    required this.podAssociateCrm,
    required this.podGeneralRemarks,
    required this.podDeskStaff,
    required this.podSpecialNotes,
    required this.podDisclaimer,
    required this.podServicingTeamName,
    required this.podPhoneCC,
    required this.podPhoneAC,
    required this.podPhoneNo,
    required this.podPhoneExtn,
    required this.podTravelDeskDetail,
    required this.podServicingTeamEmail,
    required this.psdTitleId,
    required this.psdFirstName,
    required this.psdLastName,
    required this.psdEmail,
    required this.psdPhoneCC,
    required this.psdPhoneAC,
    required this.psdPhoneNo,
    required this.psdPhoneExtn,
    required this.psdMobileCC,
    required this.psdMobileAC,
    required this.psdMobileNo,
    required this.pbdbankName,
    required this.pbdaccountNo,
    required this.pbdsortCode,
    required this.pbdbsbNo,
    required this.pbdbBranchNo,
    required this.pbdswiftCode,
    required this.pbdAddress1,
    required this.pbdAddress2,
    required this.pbdPhoneCC,
    required this.pbdPhoneAC,
    required this.pbdPhoneNo,
    required this.pbdPhoneExtn,
    required this.pbdfaxCC,
    required this.pbdfaxAC,
    required this.pbdfaxNo,
    required this.pbdfaxExtn,
    required this.plmLicenseNo,
    required this.plmServiceTax,
    required this.plmAbnNo,
    required this.plmAbnExtensionNo,
    required this.plmNpwpNumber,
    required this.ptTaxNumber,
    required this.ptTaxOutoffScope,
    required this.pgstNo,
    required this.pgstUnitCode,
    required this.pgstAgencyClassificationId,
    required this.pgstTitleId,
    required this.pgstFirstName,
    required this.pgstLastName,
    required this.pgstAddressupdate,
    required this.pgstAgencyName,
    required this.pgstAgencyAddress,
    required this.pgstCountryId,
    required this.pgstStateId,
    required this.pgstCity,
    required this.pgstPostCode,
    required this.pgstHolderEmail,
    required this.pgstPhoneCC,
    required this.pgstPhoneAC,
    required this.pgstPhoneNo,
    required this.pgstPhoneExtn,
    required this.corporateLogo,
    required this.isActive,
    required this.createdDate,
    required this.createdBy,
    required this.modifyDate,
    required this.modifyBy,
    required this.username,
    required this.password,
    required this.pccdMobileExtn,
    required this.gstNumber,
    required this.panNumber,
    required this.accountName,
    required this.accountNumber,
    required this.ifscCode,
    required this.bankName,
    required this.bankLocation,
    required this.agentId,
    required this.subAgentId,
    required this.userTypeId,
    required this.userId,
    required this.approveStatus,
    required this.vatNo,
    required this.corporateName,
    required this.stateName,
    required this.country,
    required this.operationDate,
    required this.contractType,
    required this.language,
    required this.currency,
    required this.refreshPnr,
    required this.viewPnr,
    required this.seatMap,
    required this.backofficeFile,
    required this.importBooking,
    required this.salesReport,
    required this.issueTicket,
    required this.cancelBooking,
    required this.cancelTicket,
    required this.manageServices,
    required this.manageElement,
    required this.changeBooking,
    required this.viewTicket,
    required this.downloadDocument,
    required this.bookingOptions,
    required this.agencyId,
    required this.branchId,
    required this.flightMarkup,
    required this.hotelMarkup,
    required this.carMarkup,
    required this.sightSeeingMarkup,
    required this.busMarkup,
    required this.currencyCode,
    required this.agentName,
    required this.agencyBranch,
    required this.businessUnitName,
    required this.pccdPhoneCountry,
    required this.pccdMobileCountry,
    required this.pccdFaxCountry,
    required this.pfmMobileCountry,
    required this.psdPhoneCountry,
    required this.psdMobileCountry,
    required this.pbdPhoneCountry,
    required this.pbdfaxCountry,
    required this.customerType,
    required this.customerName,
  });

  factory DelitaxModel.fromJson(Map<String, dynamic> json) {
    return DelitaxModel(
      corporateId: json['CorporateId'].toString(),
      corporate: json['Corporate'].toString(),
      accountId: json['AccountID'].toString(),
      additionalReffPrefix: json['AdditionalReffPrefix'].toString(),
      refferenceNumber: json['RefferenceNumber'].toString(),
      contractTypeId: json['ContractTypeId'].toString(),
      alternateRefferenceCode: json['AlternateRefferenceCode'].toString(),
      platformId: json['PlatformID'].toString(),
      companySecurityId: json['CompanySecurityID'].toString(),
      dateOfOperation: json['DateofOperation'].toString(),
      agencyBusinessUnitNameId: json['AgencyBusinessUnitNameID'].toString(),
      agencyBranchNameId: json['AgencyBranchNameId'].toString(),
      languageId: json['LanguageID'].toString(),
      parentCorporateId: json['ParentCorporateID'].toString(),
      businessCurrencyId: json['BusinessCurrencyID'].toString(),
      addressLine1: json['AddressLine1'].toString(),
      addressLine2: json['AddressLine2'].toString(),
      addressLine3: json['AddressLine3'].toString(),
      sububId: json['SububID'].toString(),
      city: json['City'].toString(),
      stateId: json['StateID'].toString(),
      postCode: json['PostCode'].toString(),
      countryId: json['CountryID'].toString(),
      pccdPhoneCC: json['PCCDPhoneCC'].toString(),
      pccdPhoneAC: json['PCCDPhoneAC'].toString(),
      pccdPhoneNo: json['PCCDPhoneNo'].toString(),
      pccdPhoneExtn: json['PCCDPhoneExtn'].toString(),
      pccdMobileCC: json['PCCDMobileCC'].toString(),
      pccdMobileAC: json['PCCDMobileAC'].toString(),
      pccdMobileNo: json['PCCDMobileNo'].toString(),
      pccdFaxCC: json['PCCDFaxCC'].toString(),
      pccdFaxAC: json['PCCDFaxAC'].toString(),
      pccdFaxNo: json['PCCDFaxNo'].toString(),
      pccdFaxExtn: json['PCCDFaxExtn'].toString(),
      mon: json['Mon'].toString(),
      tue: json['Tue'].toString(),
      wed: json['Wed'].toString(),
      thu: json['Thu'].toString(),
      fri: json['Fri'].toString(),
      sat: json['Sat'].toString(),
      sun: json['Sun'].toString(),
      all: json['All'].toString(),
      workingFrom: json['WorkingFrom'].toString(),
      workingTo: json['WorkingTo'].toString(),
      pfmTitleId: json['PFMTitleID'].toString(),
      pfmFirstName: json['PFMFirstName'].toString(),
      pfmLastName: json['PFMLastName'].toString(),
      pfmDepartment: json['PFMDepartment'].toString(),
      pfmDesignation: json['PFMDesignation'].toString(),
      pfmMobileCC: json['PFMMobileCC'].toString(),
      pfmMobileAC: json['PFMMobileAC'].toString(),
      pfmMobileNo: json['PFMMobileNo'].toString(),
      pfmEmail: json['PFMEmail'].toString(),
      pfmAltEmail: json['PFMAltEmail'].toString(),
      podReferredBy: json['PODReferredby'].toString(),
      podAssociateCrm: json['PODAssociateCRM'].toString(),
      podGeneralRemarks: json['PODGeneralRemarks'].toString(),
      podDeskStaff: json['PODDeskStaff'].toString(),
      podSpecialNotes: json['PODSpecialNotes'].toString(),
      podDisclaimer: json['PODDisclaimer'].toString(),
      podServicingTeamName: json['PODServicingTeamName'].toString(),
      podPhoneCC: json['PODPhoneCC'].toString(),
      podPhoneAC: json['PODPhoneAC'].toString(),
      podPhoneNo: json['PODPhoneNo'].toString(),
      podPhoneExtn: json['PODPhoneExtn'].toString(),
      podTravelDeskDetail: json['PODTravelDeskDetail'].toString(),
      podServicingTeamEmail: json['PODServicingTeamEmail'].toString(),
      psdTitleId: json['PSDTitleID'].toString(),
      psdFirstName: json['PSDFirstName'].toString(),
      psdLastName: json['PSDLastName'].toString(),
      psdEmail: json['PSDEmail'].toString(),
      psdPhoneCC: json['PSDPhoneCC'].toString(),
      psdPhoneAC: json['PSDPhoneAC'].toString(),
      psdPhoneNo: json['PSDPhoneNo'].toString(),
      psdPhoneExtn: json['PSDPhoneExtn'].toString(),
      psdMobileCC: json['PSDMobileCC'].toString(),
      psdMobileAC: json['PSDMobileAC'].toString(),
      psdMobileNo: json['PSDMobileNo'].toString(),
      pbdbankName: json['PBDBankName'].toString(),
      pbdaccountNo: json['PBDAccountNo'].toString(),
      pbdsortCode: json['PBDSortCode'].toString(),
      pbdbsbNo: json['PBDBSBNO'].toString(),
      pbdbBranchNo: json['PBDBranchNo'].toString(),
      pbdswiftCode: json['PBDSwiftCode'].toString(),
      pbdAddress1: json['PBDAddress1'].toString(),
      pbdAddress2: json['PBDAddress2'].toString(),
      pbdPhoneCC: json['PBDPhoneCC'].toString(),
      pbdPhoneAC: json['PBDPhoneAC'].toString(),
      pbdPhoneNo: json['PBDPhoneNo'].toString(),
      pbdPhoneExtn: json['PBDPhoneExtn'].toString(),
      pbdfaxCC: json['PBDFaxCC'].toString(),
      pbdfaxAC: json['PBDFaxAC'].toString(),
      pbdfaxNo: json['PBDFaxNo'].toString(),
      pbdfaxExtn: json['PBDFaxExtn'].toString(),
      plmLicenseNo: json['PLMLicenseNo'].toString(),
      plmServiceTax: json['PLMServiceTax'].toString(),
      plmAbnNo: json['PLMABNNO'].toString(),
      plmAbnExtensionNo: json['PLMABNExtensionNo'].toString(),
      plmNpwpNumber: json['PLMNPWPNumber'].toString(),
      ptTaxNumber: json['PTTaxNumber'].toString(),
      ptTaxOutoffScope: json['PTTaxOutoffScope'].toString(),
      pgstNo: json['PGSTNo'].toString(),
      pgstUnitCode: json['PGSTUnitCode'].toString(),
      pgstAgencyClassificationId: json['PGSTAgencyClassificationID'].toString(),
      pgstTitleId: json['PGSTTitleID'].toString(),
      pgstFirstName: json['PGSTFirstName'].toString(),
      pgstLastName: json['PGSTLastName'].toString(),
      pgstAddressupdate: json['PGSTAddressupdate'].toString(),
      pgstAgencyName: json['PGSTAgencyName'].toString(),
      pgstAgencyAddress: json['PGSTAgencyAddress'].toString(),
      pgstCountryId: json['PGSTCountryID'].toString(),
      pgstStateId: json['PGSTStateID'].toString(),
      pgstCity: json['PGSTCity'].toString(),
      pgstPostCode: json['PGSTPostCode'].toString(),
      pgstHolderEmail: json['PGSTHolderEmail'].toString(),
      pgstPhoneCC: json['PGSTPhoneCC'].toString(),
      pgstPhoneAC: json['PGSTPhoneAC'].toString(),
      pgstPhoneNo: json['PGSTPhoneNo'].toString(),
      pgstPhoneExtn: json['PGSTPhoneExtn'].toString(),
      corporateLogo: json['CorporateLogo'].toString(),
      isActive: json['IsActive'].toString(),
      createdDate: json['CreatedDate'].toString(),
      createdBy: json['CreatedBy'].toString(),
      modifyDate: json['ModifyDate'].toString(), // Nullable
      modifyBy: json['ModifyBy'].toString(), // Nullable
      username: json['Username'].toString(),
      password: json['Password'].toString(),
      pccdMobileExtn: json['PCCDMobileExtn'].toString(),
      gstNumber: json['GSTNumber'].toString(), // Nullable
      panNumber: json['PANNumber'].toString(), // Nullable
      accountName: json['AccountName'].toString(), // Nullable
      accountNumber: json['AccountNumber'].toString(), // Nullable
      ifscCode: json['IFSCCode'].toString(), // Nullable
      bankName: json['BankName'].toString(), // Nullable
      bankLocation: json['BankLocation'].toString(), // Nullable
      agentId: json['AgentId'].toString(), // Nullable
      subAgentId: json['SubAgentId'].toString(), // Nullable
      userTypeId: json['UserTypeId'].toString(),
      userId: json['UserId'].toString(),
      approveStatus: json['ApproveStatus'].toString(),
      vatNo: json['VATNo'].toString(),
      corporateName: json['Corporate Name'].toString(),
      stateName: json['StateName'].toString(),
      country: json['Country'].toString(),
      operationDate: json['OperationDate'].toString(),
      contractType: json['ContractType'].toString(),
      language: json['Language'].toString(),
      currency: json['Currency'].toString(),
      refreshPnr: json['RefreshPNR'].toString(),
      viewPnr: json['ViewPNR'].toString(),
      seatMap: json['SeatMap'].toString(),
      backofficeFile: json['BackofficeFile'].toString(),
      importBooking: json['ImportBooking'].toString(),
      salesReport: json['SalesReport'].toString(),
      issueTicket: json['IssueTicket'].toString(),
      cancelBooking: json['CancelBooking'].toString(),
      cancelTicket: json['CancelTicket'].toString(),
      manageServices: json['ManageServices'].toString(),
      manageElement: json['ManageElement'].toString(),
      changeBooking: json['ChangeBooking'].toString(),
      viewTicket: json['ViewTicket'].toString(),
      downloadDocument: json['DownloadDocument'].toString(),
      bookingOptions: json['BookingOptions'].toString(),
      agencyId: json['AgencyId'].toString(),
      branchId: json['BranchId'].toString(),
      flightMarkup: json['FlightMarkup'].toString(),
      hotelMarkup: json['HotelMarkup'].toString(),
      carMarkup: json['CarMarkup'].toString(),
      sightSeeingMarkup: json['SightSeeingMarkup'].toString(),
      busMarkup: json['BusMarkup'].toString(),
      currencyCode: json['CurrencyCode'].toString(),
      agentName: json['AgentName'].toString(),
      agencyBranch: json['AgencyBranch'].toString(),
      businessUnitName: json['BusinessUnitName'].toString(),
      pccdPhoneCountry: json['PCCDPhoneCountry'].toString(),
      pccdMobileCountry: json['PCCDMobileCountry'].toString(),
      pccdFaxCountry: json['PCCDFaxCountry'].toString(),
      pfmMobileCountry: json['PFMMobileCountry'].toString(),
      psdPhoneCountry: json['PSDPhoneCountry'].toString(),
      psdMobileCountry: json['PSDMobileCountry'].toString(),
      pbdPhoneCountry: json['PBDPhoneCountry'].toString(),
      pbdfaxCountry: json['PBDFaxCountry'].toString(),
      customerType: json['CustomerType'].toString(),
      customerName: json['CustomerName'].toString(),
    );
  }
}
